package io.flashapi.registry;

import java.lang.reflect.Field;

/**
 * Immutable metadata about a single entity field.
 * Computed once at startup, reused on every request.
 * The java field reference is pre-configured with setAccessible(true).
 */
public record FieldMetadata(
        String name,
        Class<?> type,
        boolean primaryKey,
        boolean autoGenerated,
        boolean hidden,
        boolean readOnly,
        boolean writeOnly,
        boolean nullable,
        boolean insertable,
        boolean updatable,
        Integer maxLength,
        Field javaField
) {
    public boolean isAcceptedInCreate() {
        return !hidden && !readOnly && insertable && (!primaryKey || !autoGenerated);
    }

    public boolean isAcceptedInUpdate() {
        return !hidden && !readOnly && !primaryKey && updatable;
    }

    public boolean isVisibleInResponse() {
        return !hidden && !writeOnly;
    }
}
